const DEVTOOLS_API_BASE_URL = "http://127.0.0.1:8000";
const DEVICE_DEBUG_API_BASE_URL = "http://10.109.233.28:8000";
const PREVIEW_API_BASE_URL = "";

module.exports = {
  DEVTOOLS_API_BASE_URL,
  DEVICE_DEBUG_API_BASE_URL,
  PREVIEW_API_BASE_URL,
};
